### ISSUE TITLE
Wiki explaining the neural network

### ISSUE THREAD

**Issue by kwhitehall** [Aerolyzer/Aerolyzer#114]
Should contain 
- a brief description of the code & reason for inclusion in code base
- brief description of the algorithm 
- current accuracy of detection associated with using the algorithm 
- point to zipfile on our Google Drive the files used for the weights

**Comment by wingarlo** [comment]
The neural network code is a combination of sigmoid neurons connected by synapses that take in histogram data as input oud outputs a single binary output.

The neural network is considered a shallow neural network as it only has a single hidden layer, similar to the one in the figure bellow.

![snn](https://user-images.githubusercontent.com/17505393/36812237-5cad9160-1c85-11e8-8f5e-85874f7ec330.png)

(Wu 2015)

The neural network I wrote uses six inputs (rgb histogram data from two portions of the sky), 13 nodes in the hidden layer, and a single output.

The reason a neural network was implemented was because I knew there was a pattern in the valid images, but looking at the numbers, I couldn't find a consistent algorithm. However, using [6 valid images and 7 invalid images](https://drive.google.com/drive/u/1/folders/1n1teuqL05TYSJc_anDikFWzr1cPfZo6_) to train this neural network, and running the data through 80,000 times, it generated synapse weights that were able to classify images with 68% accuracy.

The actual algorithm is very simple. and is just:
```
l1dup = sigm(np.dot(X,syn0))
l2dup = sigm(np.dot(l1dup,syn1))
```

Where X is the 6 inputs, syn0 is a 6x13 matrix of weights for the synapses from the input layer to the hidden layer, and syn1 is a 13x1 matrix of weights from the hidden layer to the output layer.

sigm(x) is just a sigmoid function that returns 1 / (1 + np.exp(-x)) to get a value from 0 to 1.

l2dup is assigned a value from 0 to 1. If the value is above .5, we assume the image to be valid.

With these current weights, the accuracy is 68.5% for classifying images.

Wu, Eric. “What Is the Difference between a Bayesian Network and an Artificial Neural Network?” Quora.com, 2 Feb. 2015, www.quora.com/What-is-the-difference-between-a-Bayesian-network-and-an-artificial-neural-network.

**Comment by kwhitehall** [comment]
@wingarlo please move this info into a wiki page.

**Comment by wingarlo** [comment]
Moved it [here](https://github.com/Aerolyzer/Aerolyzer/wiki/Neural-Network-Logan).

**Comment by kwhitehall** [comment]
Thanks!
