### ISSUE TITLE
redacted

### ISSUE THREAD

**Issue by khlam** [Aerolyzer/Aerolyzer#96]
redacted

**Comment by kwhitehall** [comment]
@lamki866 You do not need to add images to this repo for proof of the algorithm - those images can be placed on the Google Drive in a folder. I do not understand what you are saying about the Google Drive. The permissions are such that if a file/ folder is shared with the public, only those are viewable by the public, the rest of the drive is not exposed. You should review permissions on files and folders period. Additionally, those files are really for us to test, if you don't want to share with the public, then we don't have to share. Also to be cleaner, you can make the folder with just the images a zip file and point to it.

**Comment by lamki866** [comment]
@kwhitehall 
I've uploaded the folder of test images to the Google Drive here: https://drive.google.com/file/d/1HdPBEWozHjGKDIKbQey4To7Memu7kEUD/view

**Comment by kwhitehall** [comment]
@lamki866 where are the conversions associated with the possible security issue that you were expressing?

**Comment by lamki866** [comment]
@kwhitehall The current permissions on the OSU-Capstone google drive folder allows any Google account to view any folder or sub-directory if linked directly. This happens even if the link is generated with the option "Anyone with the link **can view**". Viewing and editing the OSU-Capstone google drive is not restricted to any accounts or a domain. 

If you don't want to restrict the permissions of the drive to our specific google accounts, we can work around this by compressing files we want to share, (such as a zip) and sharing that with the option "Anyone with the link can view".

I bring this up because I don't think root access to the AWS server is meant to be public, instructions to access it are stored in a directory.

**Comment by lamki866** [comment]
It appears that the concerns I had with Google Drive have resolved themselves as I can't reproduce it anymore. 

On the topic of OpenCV Horizon Detection by Threshold, I'm trying to come up with an algorithm to output a "score" of a submitted image; a high score being that the algorithm is confident that the image contains a horizon and a low score meaning that the image likely does not. I'm having some issues tackling this because an acceptable image of the horizon can't really be quantified in a static numeric or matrix value. This indicates to me that a machine-learning classifier approach will be better suited for horizon detection.

Given that I've already written this horizon algorithm, this is my idea to generate a "horizon score":
Recall that Horizon Detection by Threshold outlines the sky in green. There are already functions to take the pixel-area encompassed by the green outline. I'm thinking of building a confidence interval of this pixel area based on a sample size of 100+ "acceptable horizon" images. If a new image is analyzed and its contour-pixel area falls outside of the confidence interval, then it's simply rejected.
